apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nginx
    namespace: default
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: nginx
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: nginx
          internet: egress
          internet-egress-http: allow
          internet-egress-https: allow
      spec:
        containers:
        - image: nginx:stable-alpine
          name: nginx
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 50M
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: nginx
    namespace: default
  spec:
    maxReplicas: 10
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: nginx
    targetCPUUtilizationPercentage: 50
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
